set noswapfile

autocmd BufReadPost *.rs setlocal filetype=rust

let g:LanguageClient_serverCommands = {
            \ 'rust': ['cargo', 'run', '--manifest-path=/opt/rls/Cargo.toml'],
            \ }
