set noswapfile
set hidden

let g:LanguageClient_serverCommands = {
    \ 'rust': ['cargo', 'run', '--release', '--manifest-path=/opt/rls/Cargo.toml'],
    \ }

autocmd BufReadPost *.rs setlocal filetype=rust
