set nocompatible

execute 'set runtimepath+=' . expand('<sfile>:p:h:h:h')

set runtimepath+=$HOME/.fzf

set noswapfile
set hidden

let g:LanguageClient_devel = 1
let g:LanguageClient_loggingLevel = 'DEBUG'
let g:LanguageClient_serverCommands = {
    \ 'javascript': ['javascript-typescript-stdio'],
    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ }
let g:LanguageClient_selectionUI = 'location-list'
